version: '2'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: always
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - default

volumes:
  portainer_data:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/docker-data/portainer/data

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 240.30.0.0/24
          gateway: 240.30.0.1

